Check for ddcutil before executing backlight script

diff --git a/bin/executable_backlight.tmpl b/bin/executable_backlight.tmpl
--- a/bin/executable_backlight.tmpl
+++ b/bin/executable_backlight.tmpl
@@ -17,6 +17,11 @@ LAPTOP=1
 LAPTOP=0
 {{- end }}
 
+if test "$LAPTOP" -eq 0 -a -z "$(type -P -p ddcutil)"; then
+  echo -e "Error: this script requires ddcutil to function on a desktop\n\n  If you're looking for internal brightness control set LAPTOP=1" >&2
+  exit 1
+fi
+
 if [ "$LAPTOP" -ne 0 ]; then
   # Look for a proper /sys control for us to use if this is a laptop
   SYS_DIR="$(find /sys/class/backlight -maxdepth 1 -type l | head -1)"
